-- Схема базы данных системы мониторинга госзакупок.
-- Применяется на пустой базе: psql -d tender_registry -f 01_schema.sql

CREATE TYPE tender_status AS ENUM ('draft', 'active', 'won', 'lost');

CREATE TABLE companies (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    inn        text NOT NULL UNIQUE,
    is_self    boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- 10 цифр у организации, 12 у ИП и физлица.
    CONSTRAINT companies_inn_format CHECK (inn ~ '^(\d{10}|\d{12})$')
);

CREATE TABLE tenders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_number text UNIQUE,
    customer_id     bigint NOT NULL REFERENCES companies (id) ON DELETE RESTRICT,
    title           text NOT NULL,
    status          tender_status NOT NULL DEFAULT 'draft',
    published_at    timestamptz,
    bids_close_at   timestamptz,
    decided_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    -- Черновик существует только внутри трекера, на площадке его ещё нет:
    -- ни номера в реестре, ни дат процедуры.
    CONSTRAINT tenders_procedure_data_matches_status CHECK (
        (status = 'draft')
        = (registry_number IS NULL AND published_at IS NULL AND bids_close_at IS NULL)
    ),
    -- Дата итогов появляется вместе с исходом и только вместе с ним.
    CONSTRAINT tenders_decided_at_matches_status CHECK (
        (status IN ('won', 'lost')) = (decided_at IS NOT NULL)
    ),
    CONSTRAINT tenders_dates_ordered CHECK (
        (bids_close_at IS NULL OR bids_close_at > published_at)
        AND (decided_at IS NULL OR decided_at >= bids_close_at)
    )
);

CREATE TABLE lots (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_id   bigint NOT NULL REFERENCES tenders (id) ON DELETE CASCADE,
    lot_number  integer NOT NULL,
    title       text NOT NULL,
    start_price numeric(15, 2) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT lots_lot_number_positive CHECK (lot_number > 0),
    CONSTRAINT lots_start_price_positive CHECK (start_price > 0),
    CONSTRAINT lots_tender_lot_number_unique UNIQUE (tender_id, lot_number)
);

CREATE TABLE bids (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id       bigint NOT NULL REFERENCES lots (id) ON DELETE CASCADE,
    company_id   bigint NOT NULL REFERENCES companies (id) ON DELETE RESTRICT,
    amount       numeric(15, 2) NOT NULL,
    submitted_at timestamptz NOT NULL,
    is_winner    boolean NOT NULL DEFAULT false,
    CONSTRAINT bids_amount_positive CHECK (amount > 0)
);

CREATE TABLE performers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  text NOT NULL,
    inn        text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT performers_inn_format CHECK (inn ~ '^\d{12}$')
);

CREATE TABLE lot_performers (
    lot_id       bigint NOT NULL REFERENCES lots (id) ON DELETE CASCADE,
    performer_id bigint NOT NULL REFERENCES performers (id) ON DELETE RESTRICT,
    assigned_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (lot_id, performer_id)
);

COMMENT ON TABLE companies IS
    'Компании: заказчики закупок и участники, подающие ставки';
COMMENT ON COLUMN companies.is_self IS
    'Компания — владелец системы; статус тендера отражает исход её участия';
COMMENT ON TABLE tenders IS
    'Тендеры, отслеживаемые в системе';
COMMENT ON COLUMN tenders.status IS
    'Черновик, активен, выигран, проигран — исход участия своей компании';
COMMENT ON COLUMN tenders.decided_at IS
    'Дата подведения итогов; отбор выигранных тендеров за период идёт по ней';
COMMENT ON TABLE lots IS
    'Лоты тендера; ставки подаются на лот, а не на тендер целиком';
COMMENT ON TABLE bids IS
    'Ставки компаний по лотам; повторная ставка на тот же лот допускается';
COMMENT ON COLUMN bids.is_winner IS
    'Победившая ставка; на лот допускается не более одной';
COMMENT ON TABLE performers IS
    'Исполнители: физлица, самозанятые и ИП, привлекаемые на выигранные лоты';
COMMENT ON TABLE lot_performers IS
    'Назначение исполнителей на лоты';
